### ISSUE TITLE
cgcs2000不支持吗

### ISSUE THREAD

**Issue by zhanghjtx** [hujiulong/gcoord#103]

**Comment by hujiulong** [comment]
不支持，[所有支持的坐标系](https://github.com/hujiulong/gcoord#crs)

**Comment by vlev1n** [comment]
亲测可以将CGCS2000视为WGS84，转换结果基本差不多
> 我们其实很多时候直接用WGS84的坐标来代替CGCS2000坐标。因为CGCS2000的定义与WGS84实质一样。采用的参考椭球非常接近。扁率差异引起椭球面上的纬度和高度变化最大达0.1mm。当前测量精度范围内，可以忽略这点差异。[出处](https://www.jianshu.com/p/d1da05d4d44d)
