### ISSUE TITLE
gcj02转wgs84有一点误差

### ISSUE THREAD

**Issue by KingWang93** [hujiulong/gcoord#12]
![image](https://user-images.githubusercontent.com/17794023/50548102-0030f100-0c82-11e9-9c4e-4f531adc490f.png)

相差大概10几米吧

**Comment by hujiulong** [comment]
能提供一下具体的坐标值吗

**Comment by KingWang93** [comment]
> 能提供一下具体的坐标值吗
wgs84：
114.351929,30.521780;114.351906,30.521852;114.351868,30.521921;114.351822,30.521980

**Comment by davxiao** [comment]
请问最新的算法是否已经调整过了？谢谢！

**Comment by nongzhenli** [comment]
> > 能提供一下具体的坐标值吗
> > 火星坐标系：
> > 114.351929,30.521780;114.351906,30.521852;114.351868,30.521921;114.351822,30.521980

请问大佬，您这个是使用什么定位设备的呢？是否适合车载使用呀，我目前淘宝了一些gps定位天线，信号和定位精准度不太理想~

**Comment by maoAmanda** [comment]
同样存在误差，
而且我单独取点，然后将点坐标通过
<script src="https://unpkg.com/gcoord/dist/gcoord.js"></script>，
和
import { transform, WGS84, GCJ02 } from 'gcoord';
这个两个方式算出来的不一样

**Comment by zzc-tongji** [comment]
GCJ02转WGS84，这个功能严格来说是违法的。如果你位于中国大陆地区，请谨慎使用。

**Comment by hujiulong** [comment]
> GCJ02转WGS84，这个功能严格来说是违法的。如果你位于中国大陆地区，请谨慎使用。

我在README里补充了相关法律规定

**Comment by exotfboy** [comment]
请教一下，这种转换方式的原理是什么？
