### ISSUE TITLE
GCJ-2000转WGS84有误差，我估计是没办法解决的

### ISSUE THREAD

**Issue by Jaswine** [hujiulong/gcoord#14]
高德地图坐标：116.3975,39.906846（北京天安门国旗坐标）
使用gcoord转换后坐标：39.90544483458188,116.39125910334175
然后放到google地图(国外版，非cn地图)上偏移到人民大剧院了。上图
![1546664585](https://user-images.githubusercontent.com/38072426/50720562-6e463f80-10ea-11e9-828b-d27686a08665.png)

**Comment by hujiulong** [comment]
@Jaswine google地图的中国区域也是gcj02坐标系，你试试把高德地图坐标放google地图上

**Comment by hujiulong** [comment]
@Jaswine 你可以点谷歌地图左下角的卫星图像看看，卫星图像是wgs84坐标。在中国区域谷歌地图的卫星图像和普通地图坐标系不一样，是对不上的

**Comment by Jaswine** [comment]
我用的是google.com的地图，自己翻墙测试了一下，不放心，让在美国的同学也试了下。是同样的问题。我的截图中特地把我使用的地图的网址放上去了

**Comment by hujiulong** [comment]
@Jaswine 你没看明白我的意思吗？谷歌地图的中国区域就是GCJ02坐标系，不论是google.com还是google.cn。高德地图的坐标不需要做任何转换放到谷歌地图上就能对上。
