### ISSUE TITLE
pc上用百度地图得到的点坐标展示在微信的地图上有100到200米的偏差

### ISSUE THREAD

**Issue by AllenZho** [hujiulong/gcoord#15]

**Comment by hujiulong** [comment]
@AllenZho 你是怎么用的？贴代码

**Comment by AllenZho** [comment]
传入的坐标点小数点只有6位，会不会影响精确度
var point = gcoord.transform(
        [item.latitude, item.longitude],    // 经纬度坐标
        gcoord.WGS84,             // 当前坐标系
        gcoord.GCJ02             // 目标坐标系
      )

**Comment by hujiulong** [comment]
@AllenZho 仔细看文档，百度地图是BD09坐标系
```js
var point = gcoord.transform(
  [item.latitude, item.longitude],
  gcoord.BD09,
  gcoord.GCJ02
)
```

**Comment by AllenZho** [comment]
我刚刚贴错代码了，我的代码就是你这个
