### ISSUE TITLE
目前百度地图坐标系变化了，是否还能找出转化方法？

### ISSUE THREAD

**Issue by LeoLiu8023AmyLu** [hujiulong/gcoord#17]
目前 gps 坐标 转 百度地图坐标，偏移很大，而且存在缩放问题，请问是否有办法解决？

**Comment by hujiulong** [comment]
能提供一下具体的数据吗

**Comment by LeoLiu8023AmyLu** [comment]
我只有 一部分 gps 数据 [经度  纬度] 的数组，可以么？

**Comment by hujiulong** [comment]
@LeoLiu8023AmyLu 可以。另外你说的百度地图坐标变化了是什么意思，百度修改了他们的坐标系？

**Comment by LeoLiu8023AmyLu** [comment]
![image](https://user-images.githubusercontent.com/25604698/54827607-5e072f00-4ced-11e9-9f73-3126a9113ca6.png)  
类似于这样的偏移 
使用的转换是 `gcoord.WGS84 -> gcoord.BD09 `   
数据我明天整理一下

**Comment by LeoLiu8023AmyLu** [comment]
Json 文件 [[经，纬],...]  [Gps.zip](https://github.com/hujiulong/gcoord/files/2998937/Gps.zip)

**Comment by hujiulong** [comment]
> Json 文件 [[经，纬],...] [Gps.zip](https://github.com/hujiulong/gcoord/files/2998937/Gps.zip)

我在这周末看看

**Comment by hujiulong** [comment]
你这份数据似乎本身就已经是百度坐标系了，作为百度坐标系处理和道路贴合得很好
![image](https://user-images.githubusercontent.com/13267437/55288870-9b0ba980-53f0-11e9-87e0-7c9bc37ea06d.png)

**Comment by LeoLiu8023AmyLu** [comment]
> 你这份数据似乎本身就已经是百度坐标系了，作为百度坐标系处理和道路贴合得很好
> ![image](https://user-images.githubusercontent.com/13267437/55288870-9b0ba980-53f0-11e9-87e0-7c9bc37ea06d.png)

收到 十分感谢！
