### ISSUE TITLE
使用"https://unpkg.com/gcoord/dist/gcoord.js"引入不成功

### ISSUE THREAD

**Issue by LawrenceYep** [hujiulong/gcoord#18]
使用`<script src="https://unpkg.com/gcoord/dist/gcoord.js"></script>`引入时出现`Cannot find "/dist/gcoord.js" in gcoord@0.2.1`的错误。

**Comment by hujiulong** [comment]
感谢反馈，已经修复

**Comment by hujiulong** [comment]
现在最新版本是`0.2.2`，unpkg有一段缓存时间，`https://unpkg.com/gcoord/dist/gcoord.js`可能仍然会被重定向到`0.2.1`，建议用unpkg引入时带上明确的版本号：`https://unpkg.com/gcoord@0.2.2/dist/gcoord.js`

**Comment by LawrenceYep** [comment]
好的，非常感谢
