### ISSUE TITLE
support mercator projection coordinates

### ISSUE THREAD

**Issue by hujiulong** [hujiulong/gcoord#2]
支持墨卡托投影坐标

**Comment by abc2888630** [comment]
let center = [12959773,4853101];//同样用在高德和百度上
 let lonlat = ol.proj.transform(center, "EPSG:3857", "EPSG:4326"); 
//lonlat116.41962164619503,39.91157563865826，这是在高德上定位在北京天安门附件

let test = gcoord.transform(lonlat, gcoord.EPSG4326, gcoord.BD09)
//test:116.43231866009562,39.91904444259852，转换后的百度，定位到北京郊区去了

得到结果不大精确
////lonlat116.41962164619503,39.71837291000932这是自己调整后，得到的在百度地图上定位天安门附件的坐标

**Comment by hujiulong** [comment]
@abc2888630 高德地图使用的是GCJ02而不是EPSG4326，应该这样写
```js
let test = gcoord.transform( lonlat, gcoord.GCJ02, gcoord.BD09 );
```
另外有问题建议单独开一个issue
