### ISSUE TITLE
v1.0.0 版本发布之后通过 script 引入的 gcoord 函数调用发生了改变

### ISSUE THREAD

**Issue by MentalOmega** [hujiulong/gcoord#220]
https://github.com/hujiulong/gcoord/commit/782b8dea59c3db5db3073bba205f8f9705a9f125

![image](https://user-images.githubusercontent.com/30032665/212802753-f33ce60f-e339-4b58-ae87-e064cd955eef.png)

![image](https://user-images.githubusercontent.com/30032665/212802853-a3af6636-7a46-4fe8-8821-c8a195226c6b.png)

如图，现在新版的通过 script 引入的 gcoord 函数调用已经和 README.md 里面描述的不一样了

**Comment by hujiulong** [comment]
我发新版本今天处理一下

**Comment by hujiulong** [comment]
1.0.1 已经修复了
