### ISSUE TITLE
 BD09转换GCJ02坐标

### ISSUE THREAD

**Issue by puwenwan** [hujiulong/gcoord#23]
BD09转换GCJ02坐标后，大概会有15-30米左右的一个偏移，这是一个正常的偏移量么？
`[{
      "longitude": 112.95516973717,
      "latitude": 27.110248315429
    }, {
      "longitude": 112.95514967002,
      "latitude": 27.110209045353
    }, {
      "longitude": 112.9552696853,
      "latitude": 27.110439072645
    }, {
      "longitude": 112.95538827008,
      "latitude": 27.11055600291
    }, {
      "longitude": 112.95552789901,
      "latitude": 27.110607549457
    }, {
      "longitude": 112.95563435193,
      "latitude": 27.110608671425
    }, {
      "longitude": 112.95591453403,
      "latitude": 27.110596723704
    }, {
      "longitude": 112.95625794057,
      "latitude": 27.110520645541
    }, {
      "longitude": 112.95637142166,
      "latitude": 27.110518640771
    }, {
      "longitude": 112.9565491395,
      "latitude": 27.110464491862
    }, {
      "longitude": 112.95693074252,
      "latitude": 27.11043674701
    }, {
      "longitude": 112.95795897797,
      "latitude": 27.110248575302
    }, {
      "longitude": 112.95866190586,
      "latitude": 27.110180202997
    }, {
      "longitude": 112.95943518443,
      "latitude": 27.110209670777
    }, {
      "longitude": 112.96032802743,
      "latitude": 27.110363173252
    }, {
      "longitude": 112.96197014333,
      "latitude": 27.11084511094
    }, {
      "longitude": 112.96234773516,
      "latitude": 27.110922743543
    }, {
      "longitude": 112.96382982801,
      "latitude": 27.111144138779
    }, {
      "longitude": 112.96614400844,
      "latitude": 27.111540288631
    }, {
      "longitude": 112.96689684702,
      "latitude": 27.111625778344
    }, {
      "longitude": 112.96737860852,
      "latitude": 27.111681353588
    }]`
![map](https://user-images.githubusercontent.com/29518286/68660166-9e186c00-0573-11ea-9427-3b0e4ddb1037.png)

**Comment by hujiulong** [comment]
不符合预期的话可能初始坐标系或目标坐标系不对，比如这个数据可能本来就是在GCJ02坐标系下了，不需要转换

**Comment by puwenwan** [comment]
恩，坐标系应该没有问题，我从百度地图拾取一个坐标点，通过 BD09转换成GCJ02（如百度坐标116.487762,39.991447， 转换后的gcj02坐标 39.98504427818507, 116.4817478158125），腾讯地图确实会偏移 10米左右，年初就开始用大佬您的插件，那会测了很多次，偏移量非常小，绝对好使，但最近才发现，突然的就偏差大了，所以很是疑惑

**Comment by hujiulong** [comment]
你试试不做任何转换，直接展示

**Comment by nongzhenli** [comment]
最新一个项目也是正在苦苦寻找WGS84坐标转换高德地图坐标使用。上来看到大佬这么一个包、绝对start。查看说明转换偏移近乎于厘米级别？心动，等待测试...
--
感谢大佬贡献
