### ISSUE TITLE
gps坐标转BD09LL坐标和百度API的有误差。

### ISSUE THREAD

**Issue by Aroooooo** [hujiulong/gcoord#230]

**Comment by Aroooooo** [comment]
这是GPS的坐标：
[{latitude: 31.494952300000001,longitude: 104.69313101},
{latitude: 31.494962789999999,longitude: 104.6931519},
{latitude: 31.494976579999999,longitude: 104.69317904},
{latitude: 31.49499338,longitude: 104.69321239999999},
{latitude: 31.495011049999999,longitude: 104.69324896000001}
]
这是百度API转换的数据：
[{ x: 104.70239740263604, y: 31.498406132966968 },
  { x: 104.70241830315378, y: 31.498416363395064 },
  { x: 104.7024457176572, y: 31.498430096538028 },
  { x: 104.70247910340265, y: 31.49844679237374 },
  { x: 104.70251547492762, y: 31.498464563483336 }
]

这是使用gcoord转的数据：
[{ longitude: 104.70239236069166, latitude: 31.498401860432068 },
  { longitude: 104.7024133276391, latitude: 31.498412310157835 },
  { longitude: 104.70244056728582, latitude: 31.49842604835169 },
  { longitude: 104.70247404962255, latitude: 31.498442785528642 },
  { longitude: 104.7025107439927, latitude: 31.498460387839277 }
]
转换后还有不小的误差。

**Comment by hujiulong** [comment]
这看着没多大误差啊，差距都在 0.000005 度左右，差不多就几十厘米的差距
