### ISSUE TITLE
转换精度低

### ISSUE THREAD

**Issue by frankcou** [hujiulong/gcoord#231]
我试了下百度的[坐标转换](https://lbsyun.baidu.com/faq/api?title=webapi/guide/changeposition-base),发现精度对不上

"WGS84" ：121.18180305555556, 31.287874444444444 转"BD09"

百度自带的结果为：121.19272701709394,31.29222496103614

库的结果为：121.19272205711691,31.292220583538928

这会不会是js精度带来的问题？

**Comment by hujiulong** [comment]
差距在 0.000005 度左右，差不多就几十厘米的差距
