### ISSUE TITLE
原生小程序用不了，

### ISSUE THREAD

**Issue by Kai-web** [hujiulong/gcoord#232]
![image](https://github.com/hujiulong/gcoord/assets/59676989/ce5d045d-8e4c-4d44-97c7-2bfa84f4f96b)

![image](https://github.com/hujiulong/gcoord/assets/59676989/412913d6-548e-49b4-8e89-a027ac187840)

**Comment by hujiulong** [comment]
试试 1.0.6 版本，已经修复了
