### ISSUE TITLE
"CRSTypes" is not exported by "node_modules/gcoord/dist/gcoord.esm-bundler.js"

### ISSUE THREAD

**Issue by guodongAndroid** [hujiulong/gcoord#233]
在 uniapp，vue3 + ts 中使用 `import gcoord, { CRSTypes } from 'gcoord';`，编译时报错："CRSTypes" is not exported by "node_modules/gcoord/dist/gcoord.esm-bundler.js",

**Comment by flyeagleyuan** [comment]
import gcoord, { **type** CRSTypes } from 'gcoord'导出的是类型，不是常量。没有导出常量。

**Comment by guodongAndroid** [comment]
感谢回复，已经搞定了。您的库非常棒
