### ISSUE TITLE
Any difference?

### ISSUE THREAD

**Issue by chuduyunhuan** [hujiulong/gcoord#4]
Here is already one, just want to know dose this refer it or not? https://github.com/wandergis/coordtransform

**Comment by chuduyunhuan** [comment]
@wandergis

**Comment by hujiulong** [comment]
I also found this library, but gcoord has many differences from it. 
gcoord can be arbitrarily converted between coordinate systems, but coordtransform only provides `gcj02towgs84` and other methods. For example, coordtransform can not directly transform WGS84 into BD09.

here are some other features that coordtransform does not have:
1. convert geojson
2. support EPSG3857
