### ISSUE TITLE
transform参数

### ISSUE THREAD

**Issue by RuierR** [hujiulong/gcoord#43]
transform参数不支持通过网页获取到对应的当前坐标系和待转换坐标系的value 来传入方法中吗？

**Comment by hujiulong** [comment]
没明白你的意思，`transform`后面两个参数不就是当前坐标系和目标坐标系吗，你当然可以根据别的条件判断来传不同的值

**Comment by RuierR** [comment]
我想根据用户选择的值动态地进行转换 <option value ="gcoord.GCJ02"> GCJ02 </option>  然后pc_s = prest_opt.value获取到用户选择option对应的值;传入gcoord.transform(geojson, pc_s, gcoord.WGS84)，这样传入报错，我是哪里出了问题？pc_s这个值是字符串

**Comment by RuierR** [comment]
&lt;option value ="g"&gt;GCJ02 &it;/option&gt；
GCJ02那里浏览器解析了

**Comment by hujiulong** [comment]
你需要把你option的值转到gcoord的坐标系枚举值
比如这样：
```js
let origin;
if (opt.value === 'baidu') {
    origin = gcoord.BD09;
} else if (opt.value === 'google') {
    origin = gcoord.GCJ02;
}
const coord = transform([123, 45], origin, gcoord.WGS84);
```

**Comment by RuierR** [comment]
好的，谢谢，那我就用switch判断吧
