### ISSUE TITLE
距离，还是有点差距

### ISSUE THREAD

**Issue by zchd** [hujiulong/gcoord#5]
百度地图，和腾迅，还有高德还是有点差距，

**Comment by hujiulong** [comment]
请详细描述你的问题，什么场景，具体有多大的差距

**Comment by hujiulong** [comment]
和百度提供的API相比，基本上能保证经纬度小数点后5位是一致的，换成地理长度误差应该只有几十厘米，WGS84到BD09需要两次转换，这个精度应该还可以接受。
