### ISSUE TITLE
转换的原理疑问和不同坐标下瓦片的转换建议

### ISSUE THREAD

**Issue by Luooooooo** [hujiulong/gcoord#50]
1. `理论上，GCJ-02的加密过程是不可逆的，但是可以通过一些方法来逼近接原始坐标，并且这种方式的精度很高。gcoord使用的纠偏方式达到了厘米级的精度，能满足绝大多数情况`
引用wiki上的这句话，可以公布下通过哪些方法来逼近接原始坐标吗？（只是个人疑问）

2. 希望可以推出不同坐标下瓦片的转换（比如在wgs84坐标的地图上，加载在线的互联网地图会偏移）
需求是，可以矫正一些互联网地图到标准的地图上。
思路是，通过请求的url中的 {x}/{y}/{z}通过scale或者solution和zoom等计算（定位）出wgs84的瓦片的 四至，转换四至的坐标到在线地图的坐标下，再通过在线地图的坐标，计算出在线地图的瓦片。（如有错误请指正）

**Comment by hujiulong** [comment]
1.算法是在维基百科[中华人民共和国测绘限制](https://zh.wikipedia.org/zh-hans/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E6%B5%8B%E7%BB%98%E9%99%90%E5%88%B6)引用的python算法上改的，上面也有一些原理说明。

2.坐标系之间的转换不一定是线性变换，一个坐标系下的矩形，转换到另一个坐标系下并不一定是矩形，所以没办法做瓦片图的坐标转换。

**Comment by Luooooooo** [comment]
> 1.算法是在维基百科[中华人民共和国测绘限制](https://zh.wikipedia.org/zh-hans/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E6%B5%8B%E7%BB%98%E9%99%90%E5%88%B6)引用的python算法上改的，上面也有一些原理说明。
> 
> 2.坐标系之间的转换不一定是线性变换，一个坐标系下的矩形，转换到另一个坐标系下并不一定是矩形，所以没办法做瓦片图的坐标转换。

嗯，不太了解地图请求定位瓦片的方式，大致知道是分辨率solution。

我了解到另一种变形方式：在线地图是基于3857坐标系的偏移(除了百度又加了2次加密)，而3857坐标系是标准的坐标系（非加密），它有自己的椭球参数，目前只有openlayers会通过修改webgl的顶点着色器（坐标转换->webgl坐标->屏幕坐标）的方式，使图片变形，达到多个标准坐标系的图层叠加显示。
