### ISSUE TITLE
function gcoord.transfrom could not use in vue 

### ISSUE THREAD

**Issue by Brave-Zhan** [hujiulong/gcoord#64]
import gcoord :  import gcoord from "gcoord";
use gcoord: 

1. console.log(gcoord.WGS84); //correct , log: WGS84
2. gcoord.transfrom(
           [120.16336, 31.466956],
           gcoord.WGS84,
           gcoord.GCJ02
       );
//error :TypeError: gcoord.transfrom is not a function
could you help me? and how to slove the problem.

**Comment by hujiulong** [comment]
@Brave-Zhan It should be `transform`, not `transfrom `
