### ISSUE TITLE
大家有用到Cesium上不同地图底图纠偏吗？

### ISSUE THREAD

**Issue by DickyNet** [hujiulong/gcoord#79]
如题，大家有用到Cesium吗，现在我在Cesium上调用高德，谷歌中国，腾讯，百度地图，然后调用腾讯的poi接口，得到的poi兴趣点中的经纬度，显示在高德，谷歌中国，腾讯的底图上都没问题，但是显示在百度地图的底图就有偏差了，调用了转换还是偏差很大。不知道大家是怎么处理这个问题的？

gcoord.transform(
        [loc.lng, loc.lat], // 经纬度坐标
        gcoord.GCJ02, // 当前坐标系
        gcoord.BD09// 目标坐标系
      )

**Comment by kaipengHan** [comment]
使用这个库试试  https://github.com/dvgis/cesium-map
