### ISSUE TITLE
您好，GCJ-02 - 国测局坐标是CGCS2000吗？

### ISSUE THREAD

**Issue by defineconst** [hujiulong/gcoord#8]
您好，GCJ-02 - 国测局坐标和CGCS2000对应吗？谢谢！

**Comment by hujiulong** [comment]
@defineconst CGCS2000和GCJ02不对应，但是CGCS2000和WGS84非常接近，差距最大只有0.1毫米左右，完全可以认为它们是一样的。

**Comment by defineconst** [comment]
谢谢！
