### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by HFLZRH** [hujiulong/gcoord#9]
When the coordinate is transferred to GPS coordinates, there is no change. 
For example:
        var geojson = {
            "type": "Point",
            "coordinates": ["120.42378", "27.452646"]
        }
        gcoord.transform(geojson, gcoord.GCJ02, gcoord.WGS84);

**Comment by hujiulong** [comment]
@HFLZRH A standard GeoJSON object whose value of the coordinate property must be numeric.
```js
var geojson = {
  "type": "Point",
  "coordinates": [120.42378, 27.452646] // Array members must be numbers.
}
gcoord.transform(geojson, gcoord.GCJ02, gcoord.WGS84);
console.log(geojson.coordinates);  // [120.41942838920102, 27.455664850478293]
```
