### ISSUE TITLE
大地2000 经纬度转换

### ISSUE THREAD

**Issue by CHJ1993** [hujiulong/gcoord#98]
现在好多地图都开始使用大地2000的经纬坐标
大地2000 和WGS84是否有差别 
如果有能否增加一个大地2000 和各个经纬度的转换

**Comment by hujiulong** [comment]
哪些地图在使用大地2000坐标系呢？

**Comment by CHJ1993** [comment]
> 哪些地图在使用大地2000坐标系呢？

超图等好多都在用，还有一些基于arcgis扩展的一些，现在一些城市应急等场景的项目都用到大地2000

**Comment by hujiulong** [comment]
嗯，但是gcoord的目标是处理使用范围比较广的web地图中的坐标。如果需要更专业的JS坐标系处理工具，可以使用proj4js等开源库。所以这个我先close了

**Comment by vlev1n** [comment]
亲测可以将CGCS2000视为WGS84，转换结果基本差不多
> 我们其实很多时候直接用WGS84的坐标来代替CGCS2000坐标。因为CGCS2000的定义与WGS84实质一样。采用的参考椭球非常接近。扁率差异引起椭球面上的纬度和高度变化最大达0.1mm。当前测量精度范围内，可以忽略这点差异。[出处](https://www.jianshu.com/p/d1da05d4d44d)
